version: '3.8'

services:
  nginx-proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-available/:/etc/nginx/sites-available/
    container_name: ctf_challenge_proxy
    restart: unless-stopped
